### ISSUE TITLE
Cosmétique

### ISSUE THREAD

**Issue by vbonhomme** [ShakePeers/mediawiki-ReviewAndMerge#3]
SErait cool de passer "Seul l'auteur d'un article peut fusionner les révisions." avant le diff.

**Comment by Rudloff** [comment]
Pourquoi ? Ça me parait logique de l'avoir là où est normalement l'action de fusion.
On peut mettre le bouton *Merge* en grisé par contre.

**Comment by vbonhomme** [comment]
ça vient ptet du fait que je vois pas les liens alors qu'éditeur.
on pourrait pas doter les éditeurs du droit de merger ? à ce que j'en comprends, c'est pas le cas : https://github.com/ShakePeers/mediawiki-ReviewAndMerge/blob/master/SpecialReviewAndMerge.php#L206

**Comment by Rudloff** [comment]
Oui, ça si j'y travaille ^^

**Comment by vbonhomme** [comment]
ve bene ! ça simplifiera la vie des éditeurs, voire des auteurs. a minima des testeurs :o)

**Comment by Rudloff** [comment]
Voilà, j'ai ajouté un droit *reviewandmerge* aux éditeurs.
Par contre, j'ai trouvé quelques bugs dans le moteur de diff, il ne merge pas certaines modifications. Je regarde ça dans la semaine.

**Comment by vbonhomme** [comment]
marche pas pour moi, quoique dans les editeurs et avec reviewandmerge comme droit... :'(

**Comment by Rudloff** [comment]
Pas encore en prod.

**Comment by Rudloff** [comment]
Voilà, ça devrait marcher là.
